package com.jetpackages.echoverse.core.domain.model

/**
 * The "soul" of an Echo. This contains the rich, structured summary of a person's
 * communication style, generated by the AI analysis.
 */
data class PersonalityProfile(
    val id: String,
    val echoId: String,

    // Part 1: Who they are
    val coreIdentity: CoreIdentity,

    // Part 2: How they talk
    val communicationRules: CommunicationRules,

    // Part 3: What they say
    val lexicon: Lexicon,

    val sourceChatFileName: String
)

/**
 * Describes the Echo's identity and relationship with the user.
 */
data class CoreIdentity(
    val name: String,
    val relationshipToUser: String, // e.g., "Loving partner", "Close friend"
    val dailyLifeSummary: String // e.g., "Is a student, works part-time, loves cats"
)

/**
 * Defines the strict, observable rules of the Echo's communication style.
 */
data class CommunicationRules(
    val averageMessageLength: String, // e.g., "Short, 1-10 words"
    val tone: String, // e.g., "Affectionate and playful, uses dry sarcasm"
    val capitalizationStyle: String, // e.g., "Never uses capital letters"
    val punctuationStyle: String, // e.g., "Rarely uses periods, prefers emojis"
    val emojiFrequency: String // e.g., "Occasionally, 1-2 per 5 messages, not in every message"
)

/**
 * A collection of verbatim words and phrases the Echo should use.
 */
data class Lexicon(
    val signaturePhrases: List<String>, // e.g., ["'lmao of course'", "'bet'"]
    val termsOfEndearment: List<String>, // e.g., ["'baby'", "'my love'"]
    val topEmojis: List<String> // e.g., ["❤️", "😂", "😭"]
)